### ISSUE TITLE
Check the extension is released with prod assets

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-cookiecutter-ts#199]
## Description

In https://github.com/QuantStack/jupyterlab-js-logs/pull/24 we noticed the JupyterLab extension was released with development (non minified) assets.

This issue is here as a reminder to check if that's the case with this cookiecutter when we generate a brand new extension.

## Reproduce

- Generate a new extension
- Build the assets with the `jupyter-releaser`
- Check the assets in the `labextensions` folder are minified

## Context

cc @hbcarlos we can track that observation here to make sure this is handled by the cookiecutter

**Comment by hbcarlos** [comment]
Thanks! I'll look into this!

**Comment by fcollonval** [comment]
This is not happening here as can be seen on the scheduled CI run: https://github.com/jupyterlab/extension-cookiecutter-ts/runs/4934014548?check_suite_focus=true - in the log of _Install server extension from a tarball_ the assets are listed.

> You can also look at the sdist artifact.

It could indeed happen with older version of the cookiecutter due to the command `prepare` triggering the `build` command (that step was removed in the mentioned PR QuantStack/jupyterlab-js-logs#24)

**Comment by hbcarlos** [comment]
> It could indeed happen with older version of the cookiecutter due to the command prepare triggering the build command (that step was removed in the mentioned PR QuantStack/jupyterlab-js-logs#24)

Yes, but we saw that the releaser installs the extension in editable mode here:
https://github.com/jupyter-server/jupyter_releaser/blob/ca540f3441045db34d1b433c8a0714a9f97648ba/jupyter_releaser/lib.py#L565-L568
in the `prep-git` step. So we had to add this hook:
https://github.com/QuantStack/jupyterlab-js-logs/blob/84006193b64ec437d0053dcc269a4e6828c2228a/package.json#L87
to clean up the first build. Maybe we have the same trouble in every other extension.

**Comment by fcollonval** [comment]
indeed in this repo we don't test the template with the releaser. And you are making a good point. The editable mode is certainly building dev JS assets.
