### ISSUE TITLE
Include jupyter-packaging in the dependencies 

### ISSUE THREAD

**Issue by thomaslettau** [jupyterlab/extension-cookiecutter-ts#235]
When I first tried to run `jupyter labextension develop . --overwrite` I got cryptic distutils error since I had not installed ` jupyter-packaging` manually. I could only resolve the error by looking into [[environment.yml](https://github.com/jupyterlab/extension-examples/blob/master/environment.yml)](https://github.com/jupyterlab/extension-examples/blob/master/environment.yml). I have no experience with jupyter-extensions but it might be better to include ` jupyter-packaging` in either the description or the dependencies of this package.

**Comment by fcollonval** [comment]
Thanks for reporting @TheIdealis 

Could you provide some background on the version you are using? How old is the template you are using?

> The latest version is not using `jupyter-packaging`.

**Comment by thomaslettau** [comment]
My package versions are:

- jupyterlab                3.4.8
- python                    3.10.6

and I used `cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts --checkout v3.0`. Again, since I'am really inexperienced I  don't know, if I missed something but I had to install `jupyter-packaging` in order to execute `jupyter-packaging` successfully.

**Comment by fcollonval** [comment]
Did you plan to publish your extension publicly? If yes, could you write the url to the repository here? So we can have a look at the generated files.

**Comment by thomaslettau** [comment]
I think there is a misunderstanding. My installation is working, I just think that `jupyter-packaging` should be either added to the documentation or the dependencies, since `extension-cookiecutter-ts` is not working without it and the error message was rather misleading.

**Comment by bollwyvl** [comment]
Build tools (or even more aggregious all-in-one tools like `poetry`) are not great to include in library dependencies, and jupyter-packaging has kind of a rough track record for its effective versions due to the poor suggestion of `~`, which we should generally not promote in a mixed python/node environment, as the fancy operators have different meanings w.r.t number of digits, leading zeros, etc.

Adding it to an `extras_require` a la  `{{ python_package_name }}[dev]`, along with python-side formatters and linters, and updating the docs to say `python -m pip install -e .[dev]` would make it more clear that "imma doing some dev" vs "let's make a package that is easy to install".

**Comment by fcollonval** [comment]
> I think there is a misunderstanding. My installation is working, I just think that `jupyter-packaging` should be either added to the documentation or the dependencies, since `extension-cookiecutter-ts` is not working without it and the error message was rather misleading.

Indeed there is a misunderstanding because the current template version (if you look at branch 3.0) is not using `jupyter-packaging` (we move to use `hatch` and `hatch-jupyter-builder`; see https://github.com/jupyterlab/extension-cookiecutter-ts/pull/222). This is the reason I'm trying to understand why you need `jupyter-packaging` for your new extension. My guess is that you are not using the latest version - but probably an old cached version. This is the reason I'm asking if you can share the code as it will clarify that.

**Comment by thomaslettau** [comment]
Sorry for the confusion! If I remove `jupyter-packaging` from [environment.yml](https://github.com/jupyterlab/extension-examples/blob/master/environment.yml) and follow the TL;DR instructions, I get a clear warning "_Build tool `jupyter-packaging` is missing_" (I guess the examples are on an older version). If I use `cookiecutter` in this fresh environment everything works without any problems.
The problems I saw were most likely caused by my - somewhat bloated - conda environment.

**Comment by fcollonval** [comment]
Thanks for checking out @TheIdealis - we hope that indeed the new build toolchain will be more robust as it uses modern customized build system.
