### ISSUE TITLE
"jupyterlab_myextension@0.1.0" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by chfw** [jupyterlab/extension-cookiecutter-ts#32]
I just managed to follow till this section: http://jupyterlab-tutorial.readthedocs.io/en/latest/xkcd_extension_tutorial.html#build-and-install-the-extension-for-development

And got these:

"jupyterlab_myextension@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.10.0-0 <0.11.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/application

What have I done? Or is this repo out of date?

**Comment by blink1073** [comment]
Hi @chfw, it looks like the cookie cutter install picked up an older version of this repo.  I'm not a computer for the next couple of days, but will look into it when I get back.

**Comment by blink1073** [comment]
You might try seeing if there is a stale version in a ~/.cookiecutters/ directory (or Windows equivalent).

**Comment by chfw** [comment]
deleted ~/.cookiecutters/extension-cookiecutter-ts and tried again. The same outcome.

**Comment by blink1073** [comment]
Hmm, I ran the following locally:

```bash
$ rm -rf ~/.cookiecutters/

$ cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
author_name []: foo
extension_name [jupyterlab_myextension]:
project_short_description [A JupyterLab extension.]:
repository [https://github.com/my_name/jupyterlab_myextension]:

$ cat jupyterlab_myextension/package.json | grep application
    "@jupyterlab/application": "^0.13.0"

$ pip list | grep cookiecutter
cookiecutter (1.5.1)
```

If you run the above commands do those versions match?

The following worked as expected:

```bash
npm install
npm run build
jupyter labextension install
```

When I ran `jupyter lab` I saw `JupyterLab extension jupyterlab_myextension is activated!` in the browser JavaScript console.

**Comment by jandrewtorres** [comment]
I ran into this issue when creating my first extension.

JupyterLab is in pre-beta development so the default release version is rapidly changing, and this repo often is not updated to reflect the changes.

When creating an extension, be sure your environment's jupyterlab install and the cookie cutter template's jupyterlab npm package are the latest release versions.

### The solution that worked for me:

This will update the jupterlab package in the package.json file to the latest release. Run the following commands in the root directory of your extension:
```
rm -rf node_modules/
npm uninstall jupyterlab
npm install jupyterlab --save
npm install
npm run build
jupyter labextension install .
jupyter lab --watch
```

### Why I think this issue is important

- There are two tutorials that use the cookiecutter template, both of which fail to mention or address this issue, which I imagine is extremely common.
- In addition, the README for the cookie cutter repo does not provide basic set-up instructions or links to these helpful tutorials. 
- This may frustrate new contributors and hinder new extension development. Developers are scared to ask seemingly simple questions.

### Proposed solution(s):

- Alter the package.json to install the latest version of jupyterlab npm package. This allows for minimal maintenance to this cookie-cutter repo (not updating version num with every release), and in almost all cases extension development should be done with latest packages.
```
  "dependencies": {
    "jupyterlab": "latest"
  },
```
- Add a section in the README.md that addresses this issue, so if a developer has an older, incompatible version of jupyterlab that they want to develop with, they can quickly fix the issue by installing the correct version of the package via npm.
- I also think that this repo's README should include links to the two extension development tutorials in the docs, and a basic "getting started" section.

If this sounds like a good idea or not, lmk. I will gladly submit a pull request with changes.

**Comment by blink1073** [comment]
Hi @jandrewtorres, this repo is updated as part of the release checklist for JupyterLab itself (I just merged the PR that gives it compatibility with the 0.33 release).  You had the unfortunate timing of trying to use it during a release cycle.  We don't have a single top level `jupyterlab` package, but you could use `@jupyterlab/metapackage` as a shorthand, which pulls in all the packages.  

I added a `v0.33.0` tag to this repo to help with the previous versioning.  I'll update the release checklist for JupyterLab.

A PR pointing to the tutorials would be welcome, thanks!

**Comment by jandrewtorres** [comment]
@blink1073 Unfortunate timing sums up just about everything I do lol. Thanks for clearing it up. I was sure I was overthinking it a bit as I was up late trying to get going on the document-wide find and replace extension. I will submit a PR for links to extension tutorials in README tonight.

**Comment by fcollonval** [comment]
This is no more relevant => closing it. Please open a new issue, if you have trouble with the template
